local ped = createPed(71, 216.11, 117.03, 999.01)
setElementInterior(ped, 10)
setElementDimension(ped, 1)
setPedRotation(ped, 1.49)
--setPedAnimation( ped, "FOOD", "FF_Sit_Look", -1, true, false, false )
setElementData( ped, "talk", 1, false )
setElementData( ped, "name", "Guard", false )
addEventHandler("onClientPedDamage", ped, cancelEvent)
setElementFrozen(ped, true)